name       : python-google-auth-httplib2
version    : 0.0.3
release    : 1
source     :
    - https://files.pythonhosted.org/packages/e7/32/ac7f30b742276b4911a1439c5291abab1b797ccfd30bc923c5ad67892b13/google-auth-httplib2-0.0.3.tar.gz : 098fade613c25b4527b2c08fa42d11f3c2037dda8995d86de0745228e965d445
license    : Apache-2.0
component  : programming.python
summary    : Provides an httplib2 transport for google-auth
description: |
    This library provides an httplib2 transport for google-auth.
rundeps    :
    - python-google-auth
    - python-httplib2
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
