name       : python-google-auth-httplib2
version    : 0.1.0
release    : 5
source     :
    - https://github.com/googleapis/google-auth-library-python-httplib2/archive/refs/tags/v0.1.0.tar.gz : 495ab3ded76145eb5568e26cf5f84a8cec6e769d4b39547cd228fc84d0417fac
license    : Apache-2.0
component  : programming.python
summary    : Provides an httplib2 transport for google-auth
description: |
    This library provides an httplib2 transport for google-auth.
builddeps  :
    - python-setuptools
rundeps    :
    - python-google-auth
    - python-httplib2
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
